Feat section 1
jimmymut/my-brand pull request #1
Opened 2022-11-29 20:30 UTC by jimmymut

All codes of my work of HTML and CSS plus a little javascript

2022-12-02 08:26 UTC, Eli250 requested changes
First squash your commits.

2022-12-06 08:03 UTC, jimmymut commented
> First squash your commits.

I squashed them now

2022-12-06 08:11 UTC, jimmymut commented
I squashed all commits now, take a look and see if its okey

2022-12-08 13:04 UTC, Eli250 approved these changes

2022-12-08 13:05 UTC, merged